name: vmp_proxy
description: Proxy to convert between Dart VM Protocol (VMP) and Chrome Devtools Protocol (CDP).
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  vm_service_lib: ^0.3.10
  webkit_inspection_protocol: ^0.3.6

dev_dependencies:
  build_runner: 1.0.0
  build_web_compilers: any
  test: ^1.0.0
  webdev: 1.0.0
